# Mosquitto v2 Configuration for e-Sniffer Local Development & Test
# Strictly bound to localhost (127.0.0.1:1883)

listener 1883 0.0.0.0
allow_anonymous false
password_file /mosquitto/config/passwords.txt
acl_file /mosquitto/config/acl.txt

# Persistence settings
persistence true
persistence_location /mosquitto/data/

# Limits & Log
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
